#Please let the usage free, i don´t use it!
name: ServerManager
version: 3.0 BETA
author: Minecraftair | metmad22
main: de.GamerWorld.SM.Main.Main

commands: 
  sm:
    description: Main Command with many options! // "Main plugin command"
    usage:
  sminfo:
    description: Shows the information about the plugin! // "List all the information about the plugin"
    usage:
  hub:
    description: Teleport to the Hub / Spawn!
    usage: 
  sethub:
    description: Set the Hub / Spawn!
    usage:
  time:
    description: Set the time to day or night!
    usage: 
  back:
    description: Teleport to your last Location!
    usage: 
  clearinv:
    description: Clear your Inventory or the one of somebody else! 
    usage: 
    aliases: [invclear, clearinventory, inventoryclear]
  cc:
    description: Clear the chat, if you had an spammer! // "Clear the main chat"
    usage:
    aliases: [CC, ChatClear]
  head:
    description: Spawn a head of the named Player! // "Obtain a player's head!"
    usage: /head <playername>
  warp:
    description: Warp you! // "Warp to a set location"
    usage: /warp <warpname>
  com:
    description: Open the MainTeleportInventory!
    usage:
  home:
    description: Set your homes! // "Set your home(s)"
    usage:
  ban:
    description: Ban a bad player or an hacker! // "Ban a player..."
    usage:
  unban:
    description: Unban a player if you think he learned his lesson! // "Unban a player..."
    usage:
    aliases: [pardon]
  fly:
    descroption: Fly in the Survivalmode with this command! // "Enables flight mode"
    usage:
  gamemode:
    description: Set the gamemode of other players!
    usage:
    aliases: [gm]
  gms:
    description: Set your gamemode to Survival!
    usage: 
    aliases: [0]
  gmc:
    description: Set your gamemode to Creative!
    usage: 
    aliases: [1]
  gma:
    description: Set your gamemode to Adventure!
    usage: 
    aliases: [2]
  firework:
    description: Shoot a random firework!
    usage:
    aliases: [fw, firew, fwork, shootf]
  god:
    description: Makes you a god! // "Enables GOD mode!"
    usage: 
  bigtree:
    description: Spawn an big tree!
    usage:
  heal:
    description: Heal yourself or another player!
    usage:
  feed:
    description: Feed yourself!
    usage:
  broadcast:
    description: Broadcast a message to all the players!
    usage:
  burn:
    description: Burn a Player for a specified time.
    usage: /burn <Player> <Time>
  hat:
    description: Give a new hat! // "Wear a block as a hat!"
    usage:
  spawnbook:
    description: Save a startbook!
    usage:
  fireball:
    description: Fire a Fireball!
    usage:
  book:
    description: Save a book for an other player!
    usage:
  getpos:
    description: Get the Locations of an other player!
    usage:
  invsee:
    description: Look in the Inventory of an other player!
    usage:
  give:
    description: Give a player an Item!
    usage:
  item:
    description: Give yourself an Item!
    usage:
    aliases: [i]
  kick:
    description: Kick a player from the server.
    usage:
  tp:
    description: Teleport to a Player.
    usage:
  tpall:
    description: Teleport all players to your location!
    usage:
  tphere:
    description: Teleport a player to your location.
    usage:
