#Please let the usage free, i don´t use it!
name: ServerManager
version: 3.0 BETA
author: Minecraftair | medmat22
main: de.GamerWorld.SM.Main.Main

commands: 
  sm:
    description: Main Command with many options!
    usage:
  sminfo:
    description: Shows the info about the plugin!
    usage:
  hub:
    description: Teleport to the Hub / Spawn!
    usage: 
  sethub:
    description: Set the Hub / Spawn!
    usage:
  time:
    description: Set the time to day or night!
    usage: 
  back:
    description: Teleport to your last Location!
    usage: 
  clearinv:
    description: Clear your Inventory or the one of somebody else!
    usage: 
    aliases: [invclear, clearinventory, inventoryclear]
  cc:
    description: Clear the chat, if you had an spammer!
    usage:
    aliases: [CC, ChatClear]
  head:
    description: Spawn an head of the named Player!
    usage: /head <playername>
  warp:
    description: Warp you!
    usage: /warp <warpname>
  com:
    description: Open the MainTeleportInventory!
    usage:
  home:
    description: Set your homes!
    usage:
  ban:
    description: Ban an bad Player or an hacker!
    usage:
  unban:
    description: Unban an Player if you think he leard his lesson!
    usage:
    aliases: [pardon]
  fly:
    descroption: Fly in the Survivalmode with this command!
    usage:
  gamemode:
    description: Set the gamemode of other players!
    usage:
    aliases: [gm]
  gms:
    description: Set you own gamemode to Survival!
    usage: 
    aliases: [0]
  gmc:
    description: Set you own gamemode to Creativ!
    usage: 
    aliases: [1]
  gma:
    description: Set you own gamemode to Adventure!
    usage: 
    aliases: [2]
  firework:
    description: Shoot an random firework!
    usage:
    aliases: [fw, firew, fwork, shootf]
  god:
    description: Make you an god!
    usage: 
  bigtree:
    description: Spawn an bigtree!
    usage:
  heal:
    description: Heal you or another player!
    usage:
  feed:
    description: Feed your self!
    usage:
  broadcast:
    description: Broadcast an message to all Player!
    usage:
  burn:
    description: Burn an Player
    usage: /burn <Player> <Time>
  hat:
    description: Give an new hat!
    usage:
  spawnbook:
    description: Save an startbook!
    usage:
  fireball:
    description: Fire an Fireball !
    usage:
  book:
    description: Save an book for other Player!
    usage:
  getpos:
    description: Get the Locations of an other Player!
    usage:
  invsee:
    description: See the Inventory of an other Player!
    usage:
  give:
    description: Give an Player an Item!
    usage:
  item:
    description: Give yourself an Item!
    usage:
    aliases: [i]
  kick:
    description: Kick an player
    usage:
  tp:
    description: Teleport to an Player
    usage:
  tpall:
    description: Teleport all player to you!
    usage:
  tphere:
    description: Teleport an Player to you
    usage:
